[package]
name = "imd"
version = "1.1.1"
authors = ["Kevin Conley <kmancxc@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.1"

[profile.release]
lto = true
strip = true