[package]
name = "imd"
version = "1.2.0"
authors = ["Kevin Conley <koins@duck.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = ">=0.24.2"

[profile.release]
lto = true
strip = true